version: '3.1'
services:
  tenpo-challenge:
    image: 'tenpo-challenge:latest'
    build:
      context: .
    container_name: tenpo-challenge
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=tenpo
      - POSTGRES_USER=tenpo
      - POSTGRES_DB=tenpo